config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :contacts
  root to: 'images#top'
  resources :favorites, only:[:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :images do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :image

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :image, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, IconUploader
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :icon, presence: true
  before_validation { email.downcase! }

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}
  has_many :favorites, dependent: :destroy
  has_many :favorite_images, through: :favorites, source: :image
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  favorite = current_user.favorites.create(image_id: params[:image_id])
  redirect_to images_url, notice: "#{favorite.image.user.name}さんの投稿をお気に入り登録しました"
  end

def destroy
  favorite = current_user.favorites.find_by(id: params[:id]).destroy
  redirect_to images_url, notice: "#{favorite.image.user.name}さんの投稿をお気に入り解除しました"
end

def index
  @user = User.find(session[:user_id])
  @favorites_images = @user.favorites

end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
before_action :logged_in?, only: [:new, :edit, :show, :destroy]

def index
  @images = Image.all
end

def new
  if params[:back]
    @image = Image.new(image_params)
  else
    @image = Image.new
  end
end

def create
  @image = Image.new(image_params)
  @image.user_id = current_user.id
  if @image.save
    ContactMailer.contact_mail(@image).deliver
    redirect_to images_path, notice: '投稿し、投稿確認メールを送信しました'
  else
    render 'new'
  end
end

def show
  @favorite = current_user.favorites.find_by(image_id: @image.id)
end

def edit
  unless @image.user_id == current_user.id
    redirect_to images_path, notice: "権限がありません"
  end
end

def update
  if @image.update(image_params)
    redirect_to images_path, notice: '投稿を編集しました'
  else
    render 'edit'
  end
end

def destroy
  @image.destroy
  redirect_to images_path, notice: '投稿を削除しました'
end

def confirm
  @user = User.find(session[:user_id])
  @image = Image.new(image_params)
  @image.user_id = current_user.id
  render :new if @image.invalid?
end

private

def image_params
   params.require(:image).permit(:image, :content, :image_cache)
end

def set_image
@image = Image.find(params[:id])
end

def logged_in?
  unless current_user.present?
    flash[:notice] = 'ログインしてください'
    redirect_to new_session_path
  end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
user = User.find_by(email: params[:session][:email].downcase)
if user && user.authenticate(params[:session][:password])
  session[:user_id] = user.id
  redirect_to user_path(user.id)
else
  flash.now[:danger] = 'ログインに失敗しました。'
  render 'new'
end
end

def destroy
session.delete(:user_id)
flash[:notice] = 'ログアウトしました'
redirect_to new_session_path
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit, :update, :favorite]
def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to user_path(@user.id)
  else
    render 'new'
  end
end

def show
  @user = User.find(params[:id])
  @favorites_images = @user.favorites
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path, notice: "プロフィールを編集しました！"
  else
    render 'edit'
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_images_path
    elsif action_name == 'edit'
      image_path
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
     current_user.present?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit'
      user_path
    end
  end
  
end

app/views/favorites/index.html.erb
<p><%= notice %></p>
<div class ="t_menu">
<h1>お気に入り一覧</h1>
  <% @user.favorite_images.each do |image| %>
    <br>投稿者:<%= image.user.name %>
    <br><%= image_tag image.image, class: 'img-responsive' %>
    <br>コメント:<%= image.content %>
    <% end %>
</div>

app/views/images/_form.html.erb
<div class="t_menu">
<%= form_with(model: @image, local: true, url:choose_new_or_edit) do |form| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= @image.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="filed">
    <%= form.label :画像 %>
    <%= image_tag(@image.image.url, class: 'img-responsive center-block') if @image.image.url %>
    <div class ="mx-auto" style ="width: 200px;">
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  </div>
  <br>
  <div class="image_title">
    <%= form.label :内容 %>
    <%= form.text_field :content %>
  </div>
  <br>
  <%= form.submit "送信", class: 'botton' %>
<% end %>
<br>
<%= link_to "投稿一覧画面にもどる", images_path %>
</div>

app/views/images/confirm.html.erb
<div class="contants">
<div class="t_menu">

<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @image, url: images_path, local: true) do |form| %>
<%= image_tag(@image.image.url, class: 'img-responsive center-block') %>
<%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <p><%= @image.content %></p>
  <%= form.submit  "登録する", class: 'botton' %>
<% end %>

<%= form_with(model:@image, url:new_image_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back", class: 'botton' %>
<% end %>
</div>
</div>

app/views/images/edit.html.erb
<div class ="t_menu">
<h1>投稿を編集する</h1>
      <%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="text-center">
<h1>投稿一覧</h1>
<p><%= notice %></p>
<div class="container">
  <div class="row">
    <% @images.each do |image| %>
      <div class="col-xs-12 col-md-6">
        <p><%= image_tag image.image, class: 'img-responsive center-block' %></p>
        <p><%= image.content %></p>
        <p> 投稿者:<%= image.user.name %></p>

        <span><%= link_to '詳細', image_path(image.id), class:'botton' %></span>

        <% if logged_in? %>
          <% if image.user_id == current_user.id %>
            <span><%= link_to '編集', edit_image_path(image.id), data: {confirm: '本当に編集しますか？'}, class: 'botton' %></span>
            <span><%= link_to '削除', image_path(image.id),method: :delete, data: {confirm: '本当に削除しますか？'}, class:'botton' %></span>
<br>
<br>
<br>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br>
<%= link_to '新しく投稿する', new_image_path, class:'new_image' %>
</div>

app/views/images/new.html.erb
<div class = "t_menu">

<h1>投稿する</h1>
      <%= render 'form' %>
</div>

app/views/images/show.html.erb
<div class="contants">
<div class="t_menu" >

<h1>投稿詳細画面</h1>

<p><%= image_tag @image.image.url, class: 'img-responsive center-block' %></p>
<p><%= @image.content %></p>
<% unless @image.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入りを削除する', favorite_path(id: @favorite.id), method: :delete, class:'botton' %>
        <% else %>
          <%= link_to 'お気に入り', favorites_path(image_id: @image.id), method: :post, class:'botton' %>
        <% end %>
      <% end %>
      <br>

      <%= link_to "投稿一覧画面に戻る", images_path, class:'back_show' %>
</div>
</div>

app/views/images/top.html.erb
<div class = "contants">
  <div class = "t_menu">
<h1>Top</h1>
<br>
<br>
<% if logged_in? %>
<li>
  <a><%= link_to "マイページ", user_path(current_user.id), class: 'a_botton' %></a>
  </li>
  <br>
  <li>
    <a><%= link_to "投稿一覧", images_path, class: 'b_botton' %></a>
  </li>
  <br>
  <li>
    <a><%= link_to '投稿画面へ', new_image_path, class: 'a_botton' %></a>
  </li>
  <br>
  <li>
    <a><%= link_to 'お気に入り', favorites_path, class: 'b_botton' %></a>
  </li>
  <br>
  <li>
    <a><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: 'a_botton' %></a>
  </li>
<% else %>
<br>
  <li>
    <a><%= link_to "登録", new_user_path, class: 'b_botton' %></a>
  </li>
  <br>
  <li>
    <a><%= link_to "ログイン", new_session_path, class: 'a_botton' %></a>
  </li>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneTaskC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
<div class="container">
<div class="row">
  <div class="col-md-6 col-xs-12">
    <nav class="menu">
      <ul class="top_menu clearfix">
        <li>
          <a><%= link_to "topへ", root_path %></a>
        </li>

        <% if logged_in? %>
        <li>
          <a><%= link_to "マイページ", user_path(current_user.id) %></a>
          </li>
          <li>
            <a><%= link_to "投稿一覧", images_path %></a>
          </li>
          <li>
            <a><%= link_to '投稿画面へ', new_image_path %></a>
          </li>
          <li>
            <a><%= link_to 'お気に入り画面へ', favorites_path %></a>
          </li>
          <li>
            <a><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></a>
          </li>
        <% else %>
          <li>
            <a><%= link_to "登録", new_user_path %></a>
          </li>
          <li>
            <a><%= link_to "ログイン", new_session_path %></a>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>
</div>

</header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class = "container">
<div class="t_menu">

<%= form_with(model: @user, local: true ,url: new_or_edit ) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="user_edit" >
  <%= form.label :名前 %>
  <%= form.text_field :name %>
  </div>
<br>
<div class="user_edit" >
  <%= form.label :メールアドレス %>
  <%= form.email_field :email %>
  </div>
<br>
<div class="user_edit" >
  <%= form.label :パスワード %>
  <%= form.password_field :password %>
  </div>
<br>
<div class="user_edit" >
  <%= form.label :同じパスワードを入力 %>
  <%= form.password_field :password_confirmation %>
  </div>
<br>
<div class="user_edit" >
  <div class ="mx-auto" style ="width: 200px;">
  <%= form.label :ユーザー画像 %>
  <%= form.file_field :icon %>
</div>
</div>
<br>
  <%= form.submit "編集", class: 'a_botton' %>
  <%= link_to "戻る", user_path, class: 'b_botton' %>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class = "t_menu">

<h3>プロフィールの編集</h3>
<%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class = "container">
<div class ="t_menu">

<h1>登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<div class="sin_up">
  <%= f.label :名前 %>
  <%= f.text_field :name %>
</div>
<br>
<div class="sin_up">
  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>
</div>
<br>
<div class="sin_up">
  <%= f.label :パスワード %>
  <%= f.password_field :password %>
</div>
<br>
<div class="sin_up">
  <%= f.label :同じパスワードを入力 %>
  <%= f.password_field :password_confirmation %>
</div>
<br>
<div class = "field">
  <div class ="mx-auto" style ="width: 200px;">
  <%= f.label :ユーザー画像 %>
  <%= image_tag(@user.icon.url, class: 'icon') if @user.icon.url %>
  <%= f.file_field :icon %>
  </div>
  </div>
  <br>
<%= f.submit "Create my acount", class: 'botton' %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="t_menu">

<br><%= image_tag @user.icon, class: 'icon' %>
<h1><%= @user.name %>のページ</h1>
<p><%= notice %></p>
<br>
<li><%= link_to "編集", edit_user_path, class: 'botton' %></li>
<br>
<li><%= link_to "お気に入り", favorites_path, class: 'b_botton' %></li>
</div>
</div>